/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.45
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.2.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "Common_Response_Error.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {




Common_Response_Error::Common_Response_Error()
{
    m_SErrorMessage = utility::conversions::to_string_t("");
    m_SErrorMessageIsSet = false;
    m_EErrorCode = utility::conversions::to_string_t("");
    m_EErrorCodeIsSet = false;
}

Common_Response_Error::~Common_Response_Error()
{
}

void Common_Response_Error::validate()
{
    // TODO: implement validation
}

web::json::value Common_Response_Error::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_SErrorMessageIsSet)
    {
        val[utility::conversions::to_string_t("sErrorMessage")] = ModelBase::toJson(m_SErrorMessage);
    }
    if(m_EErrorCodeIsSet)
    {
        val[utility::conversions::to_string_t("eErrorCode")] = ModelBase::toJson(m_EErrorCode);
    }

    return val;
}

bool Common_Response_Error::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t("sErrorMessage")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("sErrorMessage"));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_sErrorMessage;
            ok &= ModelBase::fromJson(fieldValue, refVal_sErrorMessage);
            setSErrorMessage(refVal_sErrorMessage);
        }
    }
    if(val.has_field(utility::conversions::to_string_t("eErrorCode")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("eErrorCode"));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_eErrorCode;
            ok &= ModelBase::fromJson(fieldValue, refVal_eErrorCode);
            setEErrorCode(refVal_eErrorCode);
        }
    }
    return ok;
}

void Common_Response_Error::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }
    if(m_SErrorMessageIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("sErrorMessage"), m_SErrorMessage));
    }
    if(m_EErrorCodeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("eErrorCode"), m_EErrorCode));
    }
}

bool Common_Response_Error::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(multipart->hasContent(utility::conversions::to_string_t("sErrorMessage")))
    {
        utility::string_t refVal_sErrorMessage;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t("sErrorMessage")), refVal_sErrorMessage );
        setSErrorMessage(refVal_sErrorMessage);
    }
    if(multipart->hasContent(utility::conversions::to_string_t("eErrorCode")))
    {
        utility::string_t refVal_eErrorCode;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t("eErrorCode")), refVal_eErrorCode );
        setEErrorCode(refVal_eErrorCode);
    }
    return ok;
}

utility::string_t Common_Response_Error::getSErrorMessage() const
{
    return m_SErrorMessage;
}

void Common_Response_Error::setSErrorMessage(const utility::string_t& value)
{
    m_SErrorMessage = value;
    m_SErrorMessageIsSet = true;
}

bool Common_Response_Error::sErrorMessageIsSet() const
{
    return m_SErrorMessageIsSet;
}

void Common_Response_Error::unsetSErrorMessage()
{
    m_SErrorMessageIsSet = false;
}
utility::string_t Common_Response_Error::getEErrorCode() const
{
    return m_EErrorCode;
}

void Common_Response_Error::setEErrorCode(const utility::string_t& value)
{
    m_EErrorCode = value;
    m_EErrorCodeIsSet = true;
}

bool Common_Response_Error::eErrorCodeIsSet() const
{
    return m_EErrorCodeIsSet;
}

void Common_Response_Error::unsetEErrorCode()
{
    m_EErrorCodeIsSet = false;
}
}
}
}
}


