/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign application.  We provide SDKs for customers. They are generated using OpenAPI codegen, we encourage customers to use them as we also provide samples for them.  You can choose to build your own implementation manually or can use any compatible OpenAPI 3.0 generator like Swagger Codegen, OpenAPI codegen or any commercial generators.  If you need helping understanding how to use this API, don't waste too much time looking for it. Contact support-api@ezmax.ca, we're here to help. We are developpers so we know programmers don't like bad documentation. If you don't find what you need in the documentation, let us know, we'll improve it and put you rapidly up on track.
 *
 * The version of the OpenAPI document: 1.0.28
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.0.1-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "Ezsignsignature_editObject_v1_Request.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {




Ezsignsignature_editObject_v1_Request::Ezsignsignature_editObject_v1_Request()
{
    m_ObjEzsignsignatureIsSet = false;
}

Ezsignsignature_editObject_v1_Request::~Ezsignsignature_editObject_v1_Request()
{
}

void Ezsignsignature_editObject_v1_Request::validate()
{
    // TODO: implement validation
}

web::json::value Ezsignsignature_editObject_v1_Request::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_ObjEzsignsignatureIsSet)
    {
        val[utility::conversions::to_string_t("objEzsignsignature")] = ModelBase::toJson(m_ObjEzsignsignature);
    }

    return val;
}

bool Ezsignsignature_editObject_v1_Request::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t("objEzsignsignature")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("objEzsignsignature"));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Ezsignsignature_Request> refVal_objEzsignsignature;
            ok &= ModelBase::fromJson(fieldValue, refVal_objEzsignsignature);
            setObjEzsignsignature(refVal_objEzsignsignature);
        }
    }
    return ok;
}

void Ezsignsignature_editObject_v1_Request::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }
    if(m_ObjEzsignsignatureIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("objEzsignsignature"), m_ObjEzsignsignature));
    }
}

bool Ezsignsignature_editObject_v1_Request::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(multipart->hasContent(utility::conversions::to_string_t("objEzsignsignature")))
    {
        std::shared_ptr<Ezsignsignature_Request> refVal_objEzsignsignature;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t("objEzsignsignature")), refVal_objEzsignsignature );
        setObjEzsignsignature(refVal_objEzsignsignature);
    }
    return ok;
}

std::shared_ptr<Ezsignsignature_Request> Ezsignsignature_editObject_v1_Request::getObjEzsignsignature() const
{
    return m_ObjEzsignsignature;
}

void Ezsignsignature_editObject_v1_Request::setObjEzsignsignature(const std::shared_ptr<Ezsignsignature_Request>& value)
{
    m_ObjEzsignsignature = value;
    m_ObjEzsignsignatureIsSet = true;
}

bool Ezsignsignature_editObject_v1_Request::objEzsignsignatureIsSet() const
{
    return m_ObjEzsignsignatureIsSet;
}

void Ezsignsignature_editObject_v1_Request::unsetObjEzsignsignature()
{
    m_ObjEzsignsignatureIsSet = false;
}
}
}
}
}


