/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.46
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.2.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Field_ePhoneType.h
 *
 * The type of phone number.  **Local** refers to a north American phone number. You would then need to specify sPhoneRegion, sPhoneExchange, sPhoneNumber. **International** would be used for numbers outside of north america. You would then need to specify sPhoneInternational
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Field_ePhoneType_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Field_ePhoneType_H_


#include "../ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {

class  Field_ePhoneType
    : public ModelBase
{
public:
    Field_ePhoneType();
    virtual ~Field_ePhoneType();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    enum class eField_ePhoneType
    {
        Field_ePhoneType_LOCAL,
        Field_ePhoneType_INTERNATIONAL,
    };

    eField_ePhoneType getValue() const;
    void setValue(eField_ePhoneType const value);

    protected:
        eField_ePhoneType m_value;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Field_ePhoneType_H_ */
