/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.46
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.2.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "Field_eEzsignsignatureType.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



Field_eEzsignsignatureType::Field_eEzsignsignatureType()
{
}

Field_eEzsignsignatureType::~Field_eEzsignsignatureType()
{
}

void Field_eEzsignsignatureType::validate()
{
    // TODO: implement validation
}

web::json::value Field_eEzsignsignatureType::toJson() const
{
    web::json::value val = web::json::value::object();

    
    if (m_value == eField_eEzsignsignatureType::Field_eEzsignsignatureType_ACKNOWLEDGEMENT) val = web::json::value::string(U(Acknowledgement));
    if (m_value == eField_eEzsignsignatureType::Field_eEzsignsignatureType_CITY) val = web::json::value::string(U(City));
    if (m_value == eField_eEzsignsignatureType::Field_eEzsignsignatureType_HANDWRITTEN) val = web::json::value::string(U(Handwritten));
    if (m_value == eField_eEzsignsignatureType::Field_eEzsignsignatureType_INITIALS) val = web::json::value::string(U(Initials));
    if (m_value == eField_eEzsignsignatureType::Field_eEzsignsignatureType_NAME) val = web::json::value::string(U(Name));

    return val;
}

bool Field_eEzsignsignatureType::fromJson(const web::json::value& val)
{
    auto s = val.as_string();

    
    if (s == utility::conversions::to_string_t(Acknowledgement)) m_value = eField_eEzsignsignatureType::Field_eEzsignsignatureType_ACKNOWLEDGEMENT;
    if (s == utility::conversions::to_string_t(City)) m_value = eField_eEzsignsignatureType::Field_eEzsignsignatureType_CITY;
    if (s == utility::conversions::to_string_t(Handwritten)) m_value = eField_eEzsignsignatureType::Field_eEzsignsignatureType_HANDWRITTEN;
    if (s == utility::conversions::to_string_t(Initials)) m_value = eField_eEzsignsignatureType::Field_eEzsignsignatureType_INITIALS;
    if (s == utility::conversions::to_string_t(Name)) m_value = eField_eEzsignsignatureType::Field_eEzsignsignatureType_NAME;
    return true;
}

void Field_eEzsignsignatureType::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    utility::string_t s;

    
    if (m_value == eField_eEzsignsignatureType::Field_eEzsignsignatureType_ACKNOWLEDGEMENT) s = utility::conversions::to_string_t(Acknowledgement);
    if (m_value == eField_eEzsignsignatureType::Field_eEzsignsignatureType_CITY) s = utility::conversions::to_string_t(City);
    if (m_value == eField_eEzsignsignatureType::Field_eEzsignsignatureType_HANDWRITTEN) s = utility::conversions::to_string_t(Handwritten);
    if (m_value == eField_eEzsignsignatureType::Field_eEzsignsignatureType_INITIALS) s = utility::conversions::to_string_t(Initials);
    if (m_value == eField_eEzsignsignatureType::Field_eEzsignsignatureType_NAME) s = utility::conversions::to_string_t(Name);

    multipart->add(ModelBase::toHttpContent(namePrefix, s));
}

bool Field_eEzsignsignatureType::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }
    {
        utility::string_t s;
        ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), s);
        eField_eEzsignsignatureType v;

        
        if (s == utility::conversions::to_string_t(Acknowledgement)) v = eField_eEzsignsignatureType::Field_eEzsignsignatureType_ACKNOWLEDGEMENT;
        if (s == utility::conversions::to_string_t(City)) v = eField_eEzsignsignatureType::Field_eEzsignsignatureType_CITY;
        if (s == utility::conversions::to_string_t(Handwritten)) v = eField_eEzsignsignatureType::Field_eEzsignsignatureType_HANDWRITTEN;
        if (s == utility::conversions::to_string_t(Initials)) v = eField_eEzsignsignatureType::Field_eEzsignsignatureType_INITIALS;
        if (s == utility::conversions::to_string_t(Name)) v = eField_eEzsignsignatureType::Field_eEzsignsignatureType_NAME;

        setValue(v);
    }
    return ok;
}

Field_eEzsignsignatureType::eField_eEzsignsignatureType Field_eEzsignsignatureType::getValue() const
{
   return m_value;
}

void Field_eEzsignsignatureType::setValue(Field_eEzsignsignatureType::eField_eEzsignsignatureType const value)
{
   m_value = value;
}


}
}
}
}


