/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign application.  We provide SDKs for customers. They are generated using OpenAPI codegen, we encourage customers to use them as we also provide samples for them.  You can choose to build your own implementation manually or can use any compatible OpenAPI 3.0 generator like Swagger Codegen, OpenAPI codegen or any commercial generators.  If you need helping understanding how to use this API, don't waste too much time looking for it. Contact support-api@ezmax.ca, we're here to help. We are developpers so we know programmers don't like bad documentation. If you don't find what you need in the documentation, let us know, we'll improve it and put you rapidly up on track.
 *
 * The version of the OpenAPI document: 1.0.29
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.1.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Franchisereferalincome_createObject_v1_Request.h
 *
 * Request for the /1/object/franchisereferalincome/createObject API Request
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Franchisereferalincome_createObject_v1_Request_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Franchisereferalincome_createObject_v1_Request_H_


#include "../ModelBase.h"

#include "Franchisereferalincome_RequestCompound.h"
#include "Franchisereferalincome_Request.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// Request for the /1/object/franchisereferalincome/createObject API Request
/// </summary>
class  Franchisereferalincome_createObject_v1_Request
    : public ModelBase
{
public:
    Franchisereferalincome_createObject_v1_Request();
    virtual ~Franchisereferalincome_createObject_v1_Request();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Franchisereferalincome_createObject_v1_Request members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Franchisereferalincome_Request> getObjFranchisereferalincome() const;
    bool objFranchisereferalincomeIsSet() const;
    void unsetObjFranchisereferalincome();

    void setObjFranchisereferalincome(const std::shared_ptr<Franchisereferalincome_Request>& value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Franchisereferalincome_RequestCompound> getObjFranchisereferalincomeCompound() const;
    bool objFranchisereferalincomeCompoundIsSet() const;
    void unsetObjFranchisereferalincomeCompound();

    void setObjFranchisereferalincomeCompound(const std::shared_ptr<Franchisereferalincome_RequestCompound>& value);


protected:
    std::shared_ptr<Franchisereferalincome_Request> m_ObjFranchisereferalincome;
    bool m_ObjFranchisereferalincomeIsSet;
    std::shared_ptr<Franchisereferalincome_RequestCompound> m_ObjFranchisereferalincomeCompound;
    bool m_ObjFranchisereferalincomeCompoundIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Franchisereferalincome_createObject_v1_Request_H_ */
