/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.40
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.1.1-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "Webhook_Ezsign_FolderCompleted.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {




Webhook_Ezsign_FolderCompleted::Webhook_Ezsign_FolderCompleted()
{
    m_ObjEzsignfolderIsSet = false;
    m_ObjWebhookIsSet = false;
    m_A_objAttemptIsSet = false;
}

Webhook_Ezsign_FolderCompleted::~Webhook_Ezsign_FolderCompleted()
{
}

void Webhook_Ezsign_FolderCompleted::validate()
{
    // TODO: implement validation
}

web::json::value Webhook_Ezsign_FolderCompleted::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_ObjEzsignfolderIsSet)
    {
        val[utility::conversions::to_string_t("objEzsignfolder")] = ModelBase::toJson(m_ObjEzsignfolder);
    }
    if(m_ObjWebhookIsSet)
    {
        val[utility::conversions::to_string_t("objWebhook")] = ModelBase::toJson(m_ObjWebhook);
    }
    if(m_A_objAttemptIsSet)
    {
        val[utility::conversions::to_string_t("a_objAttempt")] = ModelBase::toJson(m_A_objAttempt);
    }

    return val;
}

bool Webhook_Ezsign_FolderCompleted::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t("objEzsignfolder")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("objEzsignfolder"));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Ezsignfolder_Response> refVal_objEzsignfolder;
            ok &= ModelBase::fromJson(fieldValue, refVal_objEzsignfolder);
            setObjEzsignfolder(refVal_objEzsignfolder);
        }
    }
    if(val.has_field(utility::conversions::to_string_t("objWebhook")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("objWebhook"));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Webhook_Response> refVal_objWebhook;
            ok &= ModelBase::fromJson(fieldValue, refVal_objWebhook);
            setObjWebhook(refVal_objWebhook);
        }
    }
    if(val.has_field(utility::conversions::to_string_t("a_objAttempt")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("a_objAttempt"));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<Attempt_Response>> refVal_a_objAttempt;
            ok &= ModelBase::fromJson(fieldValue, refVal_a_objAttempt);
            setAObjAttempt(refVal_a_objAttempt);
        }
    }
    return ok;
}

void Webhook_Ezsign_FolderCompleted::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }
    if(m_ObjEzsignfolderIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("objEzsignfolder"), m_ObjEzsignfolder));
    }
    if(m_ObjWebhookIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("objWebhook"), m_ObjWebhook));
    }
    if(m_A_objAttemptIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("a_objAttempt"), m_A_objAttempt));
    }
}

bool Webhook_Ezsign_FolderCompleted::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(multipart->hasContent(utility::conversions::to_string_t("objEzsignfolder")))
    {
        std::shared_ptr<Ezsignfolder_Response> refVal_objEzsignfolder;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t("objEzsignfolder")), refVal_objEzsignfolder );
        setObjEzsignfolder(refVal_objEzsignfolder);
    }
    if(multipart->hasContent(utility::conversions::to_string_t("objWebhook")))
    {
        std::shared_ptr<Webhook_Response> refVal_objWebhook;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t("objWebhook")), refVal_objWebhook );
        setObjWebhook(refVal_objWebhook);
    }
    if(multipart->hasContent(utility::conversions::to_string_t("a_objAttempt")))
    {
        std::vector<std::shared_ptr<Attempt_Response>> refVal_a_objAttempt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t("a_objAttempt")), refVal_a_objAttempt );
        setAObjAttempt(refVal_a_objAttempt);
    }
    return ok;
}

std::shared_ptr<Ezsignfolder_Response> Webhook_Ezsign_FolderCompleted::getObjEzsignfolder() const
{
    return m_ObjEzsignfolder;
}

void Webhook_Ezsign_FolderCompleted::setObjEzsignfolder(const std::shared_ptr<Ezsignfolder_Response>& value)
{
    m_ObjEzsignfolder = value;
    m_ObjEzsignfolderIsSet = true;
}

bool Webhook_Ezsign_FolderCompleted::objEzsignfolderIsSet() const
{
    return m_ObjEzsignfolderIsSet;
}

void Webhook_Ezsign_FolderCompleted::unsetObjEzsignfolder()
{
    m_ObjEzsignfolderIsSet = false;
}
std::shared_ptr<Webhook_Response> Webhook_Ezsign_FolderCompleted::getObjWebhook() const
{
    return m_ObjWebhook;
}

void Webhook_Ezsign_FolderCompleted::setObjWebhook(const std::shared_ptr<Webhook_Response>& value)
{
    m_ObjWebhook = value;
    m_ObjWebhookIsSet = true;
}

bool Webhook_Ezsign_FolderCompleted::objWebhookIsSet() const
{
    return m_ObjWebhookIsSet;
}

void Webhook_Ezsign_FolderCompleted::unsetObjWebhook()
{
    m_ObjWebhookIsSet = false;
}
std::vector<std::shared_ptr<Attempt_Response>>& Webhook_Ezsign_FolderCompleted::getAObjAttempt()
{
    return m_A_objAttempt;
}

void Webhook_Ezsign_FolderCompleted::setAObjAttempt(const std::vector<std::shared_ptr<Attempt_Response>>& value)
{
    m_A_objAttempt = value;
    m_A_objAttemptIsSet = true;
}

bool Webhook_Ezsign_FolderCompleted::aObjAttemptIsSet() const
{
    return m_A_objAttemptIsSet;
}

void Webhook_Ezsign_FolderCompleted::unsetA_objAttempt()
{
    m_A_objAttemptIsSet = false;
}
}
}
}
}


